### ISSUE TITLE
忽略某个方法下所有的sql语句添加tenantId字段，如何处理?

### ISSUE THREAD

**Issue by jiaopeng** [osinn/druid-multi-tenant-starter#2]
现有的功能除了再mapper接口上添加注解忽略tenantId字段外，能否支持忽略某个方法下所有的sql语句添加tenantId字段？
如系统初始化方法init()，获取全量数据、缓存数据等，init()方法内有获取不同表中的数据。

**Comment by osinn** [comment]
> 现有的功能除了再mapper接口上添加注解忽略tenantId字段外，能否支持忽略某个方法下所有的sql语句添加tenantId字段？ 如系统初始化方法init()，获取全量数据、缓存数据等，init()方法内有获取不同表中的数据。

不能支持。插件是从Mybatis执行一条SQL语句纬度进行拦截串改，init()方法内要是执行不同的查询需要在不同方法上指明需要忽略tenantId字段
